-- Crear la base de datos
CREATE DATABASE TIENDA;

-- Seleccionar la base de datos
USE TIENDA;

-- Crear la tabla Cliente
CREATE TABLE CLIENTE (
    CLIENTE_ID INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE NVARCHAR(50),
    APELLIDO NVARCHAR(50),
    DNI NVARCHAR(15)
);

-- Crear la tabla Articulo
CREATE TABLE ARTICULO (
    ARTICULO_ID INT PRIMARY KEY IDENTITY(1,1),
	CODIGO_ARTICULO NVARCHAR (12),
    NOMBRE_ARTICULO NVARCHAR(100),
    CATEGORIA NVARCHAR(50),
    PRECIO_UNITARIO DECIMAL(10,2)
);

-- Crear la tabla OrdenDeCompra
CREATE TABLE ORDEN_COMPRA (
    ORDEN_ID INT PRIMARY KEY IDENTITY(1,1),
    CLIENTE_ID INT FOREIGN KEY REFERENCES CLIENTE(CLIENTE_ID),
    FECHA_COMPRA DATETIME
);

-- Crear la tabla DetalleOrdenCompra para la relación muchos a muchos entre OrdenDeCompra y Articulo
CREATE TABLE DETALLE_ORDEN_COMPRA (
    DETALLE_ID INT PRIMARY KEY IDENTITY(1,1),
    ORDEN_ID INT,
    ARTICULO_ID INT,
    CANTIDAD INT,
    FOREIGN KEY (ORDEN_ID) REFERENCES ORDEN_COMPRA(ORDEN_ID),
    FOREIGN KEY (ARTICULO_ID) REFERENCES ARTICULO(ARTICULO_ID)
);
